### ISSUE TITLE
Telepathy plugin causes crash on first load

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#152]
When starting media-explorer from cold I get:

(lt-media-explorer:3610): tp-glib-CRITICAL **: tp_connection_dup_contact_list: assertion `TP_IS_CONNECTION (self)' failed
#0  [mex_debug_log_handler+0x4a]
#1  [g_logv+0x1fe]
#2  [g_log+0x32]
#3  [g_return_if_fail_warning+0x3d]
#4  [tp_connection_dup_contact_list+0x59]
#5  [mex_telepathy_plugin_on_connection_ready+0xa6]
#6  [mex_telepathy_plugin_on_account_status_changed+0x86]
#7  [tp_error_get_dbus_name+0x44ff]
#8  [g_closure_invoke+0x192]
#9  [g_signal_handler_disconnect+0x1888]
#10  [g_signal_emit_valist+0x806]
#11  [g_signal_emit+0x32]
#12  [tp_account_get_feature_quark_connection+0xea6]
#13  [<no name>+0xea6]
#14  [tp_proxy_pending_call_v0_take_results+0x70f]
#15  [g_list_sort_with_data+0xa1]
#16  [g_main_context_dispatch+0x1d2]
#17  [g_main_context_dispatch+0x9b0]
#18  [g_main_loop_run+0x183]
#19  [clutter_main+0x115]
#20  [mx_application_run+0xbc]
#21  [main+0x1e84]
#22  [__libc_start_main+0xe6]
#23  [_start+0x21]

Segmentation fault

**Comment by jpwhiting** [comment]
Interesting I don't get the same with mex master I just built here.  What version of telepathy-glib are you using? I'm using libtelepathy-glib 0.15.5-1 from debian package.

**Comment by ghost** [comment]
Yep I'm using the same version.

Package: libtelepathy-glib0
Architecture: i386
Source: telepathy-glib
Version: 0.15.5-1

mex starts up and loads the plugin on the second try so it sounds like some sort of initialisation problem.

**Comment by ghost** [comment]
More backtrace: connection=0x0 

```
Program received signal SIGSEGV, Segmentation fault.
0xabe4f2a4 in mex_telepathy_plugin_on_connection_ready (connection=0x0, 
    error=0x0, user_data=0x871c650) at telepathy/mex-telepathy-plugin.c:549
549   for (i = 0; i < contacts->len; i++)
(gdb) bt
#0  0xabe4f2a4 in mex_telepathy_plugin_on_connection_ready (connection=0x0, 
    error=0x0, user_data=0x871c650) at telepathy/mex-telepathy-plugin.c:549
#1  0xabe4f383 in mex_telepathy_plugin_on_account_status_changed (
    account=0x887a0f8, old_status=1, new_status=0, reason=1, 
    dbus_error_name=0x0, details=0x890a8f0, user_data=0x871c650)
    at telepathy/mex-telepathy-plugin.c:582
#2  0xab26a46f in ?? () from /usr/lib/libtelepathy-glib.so.0
#3  0xb73b09f2 in g_closure_invoke (closure=0x86a48a8, return_value=0x0, 
    n_param_values=6, param_values=0x88bcc80, invocation_hint=0xbfffec60)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gclosure.c:767
#4  0xb73c3988 in signal_emit_unlocked_R (node=0x86aacd8, detail=0, 
    instance=0x887a0f8, emission_return=0x0, instance_and_params=0x88bcc80)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gsignal.c:3252
#5  0xb73cc3f6 in g_signal_emit_valist (instance=0x887a0f8, signal_id=268, 
    detail=0, 
    var_args=0xbfffee30 "\370\240\207\b\220\256g\bs\016(\253\316\f(\253")
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gsignal.c:2983
#6  0xb73cc5a2 in g_signal_emit (instance=0x887a0f8, signal_id=268, detail=0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gsignal.c:3040
#7  0xab17c896 in ?? () from /usr/lib/libtelepathy-glib.so.0
#8  0xab178af2 in ?? () from /usr/lib/libtelepathy-glib.so.0
#9  0xab25784f in ?? () from /usr/lib/libtelepathy-glib.so.0
#10 0xb72f5a41 in g_idle_dispatch (source=0x878bcf8, callback=0xab2577c0, 
    user_data=0x84d27d0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:4545
#11 0xb72fa252 in g_main_dispatch (context=0x83c2de0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:2440
#12 g_main_context_dispatch (context=0x83c2de0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:3013
#13 0xb72faa30 in g_main_context_iterate (context=0x83c2de0, block=1, 
    dispatch=1, self=<value optimized out>)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:3091
#14 0xb72fb0f3 in g_main_loop_run (loop=0x88f11f0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:3299
#15 0xb7d7ee25 in clutter_main () at ./clutter-main.c:675
#16 0xb7eb9bdc in mx_application_run (application=0x8074458)
    at ../mx/mx-application.c:704
#17 0x0805444c in main (argc=1, argv=0xbffff374) at mex-main.c:2620
```

**Comment by ghost** [comment]
Tried the branch as suggested here is the new bracktrace:

```
Program received signal SIGSEGV, Segmentation fault.
0xab64d2ae in mex_telepathy_plugin_on_connection_ready (connection=0x89d79d0, 
    params=0x8ab9bb8, self=0x871ba50) at telepathy/mex-telepathy-plugin.c:541
541   for (i = 0; i < contacts->len; i++)
(gdb) p connection
$1 = (TpConnection *) 0x89d79d0
(gdb) p *connection
$2 = {parent = {parent = {g_type_instance = {g_class = 0x875d328}, 
      ref_count = 4, qdata = 0x84c7dc0}, dbus_daemon = 0x871baa0, 
    dbus_connection = 0x84f1bf4, 
    bus_name = 0x89ddae8 "org.freedesktop.Telepathy.AccountManager", 
    object_path = 0x89ddb60 "/org/freedesktop/Telepathy/Account/salut/local_xmpp/account0", invalidated = 0x0, priv = 0x89d79f8}, priv = 0x89d7a18}
(gdb) bt
#0  0xab64d2ae in mex_telepathy_plugin_on_connection_ready (
    connection=0x89d79d0, params=0x8ab9bb8, self=0x871ba50)
    at telepathy/mex-telepathy-plugin.c:541
#1  0xb73cd728 in g_cclosure_marshal_VOID__PARAM (closure=0x8ac4d98, 
    return_value=0x0, n_param_values=2, param_values=0x863b028, 
    invocation_hint=0xbfffeba0, marshal_data=0x0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gmarshal.c:533
#2  0xb73b09f2 in g_closure_invoke (closure=0x8ac4d98, return_value=0x0, 
    n_param_values=2, param_values=0x863b028, invocation_hint=0xbfffeba0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gclosure.c:767
#3  0xb73c3988 in signal_emit_unlocked_R (node=0x8060160, detail=2098, 
    instance=0x89d79d0, emission_return=0x0, instance_and_params=0x863b028)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gsignal.c:3252
#4  0xb73cc3f6 in g_signal_emit_valist (instance=0x89d79d0, signal_id=1, 
    detail=2098, 
    var_args=0xbfffed60 "\204\367\070\267\300af\b\300}L\b<\260>\267\320y\235\b\001")
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gsignal.c:2983
#5  0xb73cc5a2 in g_signal_emit (instance=0x89d79d0, signal_id=1, detail=2098)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gsignal.c:3040
#6  0xb73b2771 in g_object_dispatch_properties_changed (object=0x89d79d0, 
    n_pspecs=1, pspecs=0xbfffedf0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gobject.c:925
#7  0xb73b1a6f in g_object_notify_dispatcher (object=0x89d79d0, n_pspecs=1, 
    pspecs=0xbfffedf0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gobject.c:330
#8  0xb73b4a81 in g_object_notify_queue_thaw (object=0x89d79d0, 
    property_name=0xab455ea5 "connection")
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gobjectnotifyqueue.c:132
#9  g_object_notify_by_spec_internal (object=0x89d79d0, 
    property_name=0xab455ea5 "connection")
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gobject.c:983
#10 g_object_notify (object=0x89d79d0, property_name=0xab455ea5 "connection")
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gobject/gobject.c:1024
#11 0xab3464fc in ?? () from /usr/lib/libtelepathy-glib.so.0
#12 0xb744ca09 in g_simple_async_result_complete (simple=0xb4eeb418)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gio/gsimpleasyncresult.c:747
#13 0xb744cb2d in complete_in_idle_cb (data=0xb4eeb418)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./gio/gsimpleasyncresult.c:757
#14 0xb72f5a41 in g_idle_dispatch (source=0x8a099a8, 
    callback=0xb744cb10 <complete_in_idle_cb>, user_data=0xb4eeb418)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:4545
#15 0xb72fa252 in g_main_dispatch (context=0x83c2de0)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:2440
#16 g_main_context_dispatch (context=0x83c2de0)
---Type <return> to continue, or q <return> to quit---
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:3013
#17 0xb72faa30 in g_main_context_iterate (context=0x83c2de0, block=1, 
    dispatch=1, self=<value optimized out>)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:3091
#18 0xb72fb0f3 in g_main_loop_run (loop=0x8ab5d10)
    at /build/buildd-glib2.0_2.28.6-1-i386-A3fp41/glib2.0-2.28.6/./glib/gmain.c:3299
#19 0xb7d7ee25 in clutter_main () at ./clutter-main.c:675
#20 0xb7eb9b5c in mx_application_run (application=0x8074458)
    at ../mx/mx-application.c:704
#21 0x0805444c in main (argc=1, argv=0xbffff374) at mex-main.c:2620
```

**Comment by jpwhiting** [comment]
Ok, I was able to recreate that crash after rebooting.  I discussed the problem with some telepathy developers and a fix is on the branch.  However it requires telepathy-glib 0.15.6 for the initial contact list to appear in some cases (it worked fine here, but I don't have any link-local contacts).

**Comment by dlespiau** [comment]
I believe this has been fixed in master?

Also, if the telepathy-glib dependency needs a bump, don't forget to do it in the configure.ac :p

**Comment by jpwhiting** [comment]
Yep, fixed.  I'll close this and update the tp-glib dependency. thanks for reminding me.
