### ISSUE TITLE
Play on album group segfaults

### ISSUE THREAD

**Issue by michaelwood** [media-explorer/media-explorer#187]
"Play" action on an album:

```
Program received signal SIGSEGV, Segmentation fault.
0xb73a3945 in g_type_interfaces (type=2822608728, n_interfaces=0xbfffe548)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gtype.c:3574
3574    /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gtype.c: No such file or directory.
    in /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gtype.c
(gdb) bt
#0  0xb73a3945 in g_type_interfaces (type=2822608728, n_interfaces=0xbfffe548)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gtype.c:3574
#1  0xb739a2e8 in signal_id_lookup (itype=2822608728, quark=<optimized out>)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:337
#2  signal_parse_name (detail_p=<synthetic pointer>, itype=2822608728, 
    name=0xb7fc5e15 "notify", force_quark=<optimized out>)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:983
#3  signal_parse_name (force_quark=1, detail_p=<synthetic pointer>, 
    itype=2822608728, name=0xb7fc5e15 "notify")
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:2250
#4  g_signal_connect_data (instance=0xa83e8700, 
    detailed_signal=0xb7fc5e15 "notify", 
    c_handler=0xb7fb44bd <content_notify_cb>, data=0x8d7f080, destroy_data=0, 
    connect_flags=0)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:2272
#5  0xb7fb3237 in mex_view_model_set_model (self=0x8d7f080, model=0x83dda40)
    at mex-view-model.c:127
#6  0xb7fb34ca in mex_view_model_set_property (object=0x8d7f080, 
    property_id=1, value=0xbfffe6dc, pspec=0x8733b90) at mex-view-model.c:196
#7  0xb73868c6 in object_set_property (nqueue=0x896d460, value=0xa388357c, 
    pspec=0x8733b90, object=0x8d7f080)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gobject.c:1199
#8  g_object_newv (object_type=141083592, n_parameters=1, 
    parameters=0xa3883578)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gobject.c:1525
#9  0xb73875c3 in g_object_new_valist (object_type=141083592, 
    first_property_name=0xb7fc5f7f "model", 
    var_args=0xbfffe7f0 "\330(<\267\330(<\267H\350\377\277}\032\005\b@\332=\b\270\071\005\b\020\333;\b\330(<\267\230\201\342\250h\rp\265\300]F\bƄ:\267\230\201\342\250Q{\037\267Пn\265Пn\265\220@\b\b\360\262\342\250@\332=\b`\232\354\250\360\262\342\250\330(<\267")
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gobject.c:1610
#10 0xb7387820 in g_object_new (object_type=141083592, 
    first_property_name=0xb7fc5f7f "model")
---Type <return> to continue, or q <return> to quit---   
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gobject.c:1325
#11 0xb7fb3efc in mex_view_model_new (model=0x83dda40) at mex-view-model.c:486
#12 0x08051a7d in mex_open_group_cb (action=0x8508800, data=0xbffff1dc)
    at mex-main.c:1949
#13 0xb73818ec in g_cclosure_marshal_VOID__VOID (closure=0xb5700d68, 
    return_value=0x0, n_param_values=1, param_values=0xa8e28198, 
    invocation_hint=0xbfffe970, marshal_data=0x0)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gmarshal.c:85
#14 0xb73803dc in g_closure_invoke (closure=0xb5700d68, return_value=0x0, 
    n_param_values=1, param_values=0xa8e28198, invocation_hint=0xbfffe970)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gclosure.c:774
#15 0xb7393180 in signal_emit_unlocked_R (node=0x8516590, detail=0, 
    instance=0x8508800, emission_return=0x0, instance_and_params=0xa8e28198)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:3272
#16 0xb739bf17 in g_signal_emit_valist (instance=0x8508800, signal_id=39, 
    detail=0, var_args=0xbfffeba8 "")
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:3003
#17 0xb739c20f in g_signal_emit_by_name (instance=0x8508800, 
    detailed_signal=0xb7f1df96 "activated")
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:3097
#18 0xb7ecf522 in mx_button_pull (button=0x8d78098) at ../mx/mx-button.c:315
#19 0xb7ecf5c9 in mx_button_key_release (actor=0x8d78098, event=0xa7d4d5d8)
    at ../mx/mx-button.c:386
#20 0xb7dce0e2 in _clutter_marshal_BOOLEAN__BOXED (closure=0x85713e0, 
    return_value=0xbfffed44, n_param_values=2, param_values=0xa753c718, 
    invocation_hint=0xbfffed30, marshal_data=0xb7ecf590)
    at clutter-marshal.c:85
#21 0xb737ee2d in g_type_class_meta_marshal (closure=0x85713e0, 
    return_value=0xbfffed44, n_param_values=2, param_values=0xa753c718, 
    invocation_hint=0xbfffed30, marshal_data=0x9c)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gclosure.c:885
#22 0xb73803dc in g_closure_invoke (closure=0x85713e0, 
    return_value=0xbfffed44, n_param_values=2, param_values=0xa753c718, 
    invocation_hint=0xbfffed30)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gclos---Type <return> to continue, or q <return> to quit---
ure.c:774
#23 0xb7392fc8 in signal_emit_unlocked_R (node=0x8571600, detail=0, 
    instance=0x8d78098, emission_return=0xbfffee7c, 
    instance_and_params=0xa753c718)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:3310
#24 0xb739bd29 in g_signal_emit_valist (instance=0x8d78098, signal_id=65, 
    detail=0, var_args=0xbfffeef0 "\f\357\377\277")
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:3013
#25 0xb739c083 in g_signal_emit (instance=0x8d78098, signal_id=65, detail=0)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./gobject/gsignal.c:3060
#26 0xb7d40f17 in clutter_actor_event (actor=0x8d78098, event=0xa7d4d5d8, 
    capture=0) at ./clutter-actor.c:8702
#27 0xb7d886f9 in emit_event (is_key_event=1, event=0xa7d4d5d8)
    at ./clutter-main.c:1967
#28 emit_keyboard_event (event=0xa7d4d5d8) at ./clutter-main.c:2017
#29 _clutter_process_event_details (event=0xa7d4d5d8, stage=<optimized out>, 
    context=<optimized out>) at ./clutter-main.c:2107
#30 _clutter_process_event (event=0xa7d4d5d8) at ./clutter-main.c:2330
#31 0xb7da34d0 in _clutter_stage_process_queued_events (stage=0x8573958)
    at ./clutter-stage.c:898
#32 0xb7d8a307 in clutter_clock_dispatch (source=0x85749b8, callback=0, 
    user_data=0x0) at ./clutter-master-clock.c:360
#33 0xb72aab1f in g_main_dispatch (context=0x806db20)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./glib/gmain.c:2441
#34 g_main_context_dispatch (context=0x806db20)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./glib/gmain.c:3011
#35 0xb72ab250 in g_main_context_iterate (context=0x806db20, 
    block=-1221878736, dispatch=1, self=<optimized out>)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./glib/gmain.c:3089
#36 0xb72ab85b in g_main_loop_run (loop=0xb57092a0)
    at /build/buildd-glib2.0_2.30.2-1-i386-R_yvdj/glib2.0-2.30.2/./glib/gmain.c:3297
#37 0xb7d86cd5 in clutter_main () at ./clutter-main.c:676
#38 0xb7ec4fbc in mx_application_run (application=0x8075860)
    at ../mx/mx-application.c:704
#39 0x080532c8 in main (argc=1, argv=0xbffff354) at mex-main.c:2580
```

**Comment by thos** [comment]
Do you still have this issue? I recently fixed the album groups so that they open in the player.

**Comment by ghost** [comment]
WFM
