### ISSUE TITLE
Memory error  GSlice: assertion failed

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#86]
``` stdout
***MEMORY-ERROR***: lt-mex[5239]: GSlice: assertion failed: sinfo->n_allocated > 0

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x8047b70 (LWP 5921)]
0xb7fe2424 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7fe2424 in __kernel_vsyscall ()
#1  0xb72a2911 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#2  0xb72a5d42 in abort () at abort.c:92
#3  0xb7557abf in ?? () from /lib/libglib-2.0.so.0
#4  0xb7557c3a in ?? () from /lib/libglib-2.0.so.0
#5  0xb7558174 in ?? () from /lib/libglib-2.0.so.0
#6  0xb7558369 in ?? () from /lib/libglib-2.0.so.0
#7  0xb77436af in __nptl_deallocate_tsd () at pthread_create.c:155
#8  0xb7743c47 in start_thread (arg=0x8047b70) at pthread_create.c:311
#9  0xb734493e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:130
```

**Comment by ghost** [comment]
Any way to reproduce ?

**Comment by rbradford** [comment]
Michael, you don't have glib debugging symbols installed. Would be a good idea to get those installed ;-)

**Comment by ghost** [comment]
yeah, I was using my system glib and realised they weren't installed, haven't been able to reproduce it yet. I was just using mex at home.
